---
apiVersion: v1
kind: Service
metadata:
  name: deploy-redis
  namespace: deploy
  labels:
    k8s-app: deploy-redis
spec:
  externalIPs:
  - 77.80.255.100
  ports:
  - port: 1338
    protocol: TCP
    targetPort: 1338
  selector:
    k8s-app: deploy-redis
  type: ClusterIP

