apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: puppetboard
  name: puppetboard
  namespace: puppet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: puppetboard
    spec:
      containers:
      - image: quay.io/dhtech/dhauth
        imagePullPolicy: Always
        name: dhauth
        env:
        - name: APACHE_PROXY_PORT
          value: "8080"
      - image: quay.io/dhtech/puppetboard
        imagePullPolicy: Always
        name: puppetboard
        volumeMounts:
          - mountPath: "/puppetdb-keys"
            name: puppetdb-keys
        env:
          - name: PUPPETBOARD_PORT
            value: "8080"
          - name: PUPPETDB_HOST
            value: "puppet.tech.dreamhack.se"
          - name: PUPPETDB_PORT
            value: "8081"
          - name: PUPPETDB_SSL_VERIFY
            value: "/puppetdb-keys/ca.pem"
          - name: PUPPETDB_KEY
            value: "/puppetdb-keys/private.pem"
          - name: PUPPETDB_CERT
            value: "/puppetdb-keys/public.pem"
          - name: INVENTORY_FACTS
            value: "Hostname,fqdn, IP Address,ipaddress"
          - name: ENABLE_CATALOG
            value: "true"
          - name: GRAPH_FACTS
            value: "architecture,puppetversion,osfamily"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
      restartPolicy: Always
      volumes:
        - name: puppetdb-keys
          secret:
            secretName: puppetdb-keys
            defaultMode: 256 # 0400 in decimal
