kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data
  namespace: monitoring
  labels:
    k8s-app: prometheus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
