apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: wiki
    namespace: wiki
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: admin
subjects:
  - kind: ServiceAccount
    name: wiki
    namespace: wiki
