apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: wiki
  name: wiki
  namespace: wiki
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      k8s-app: wiki
  template:
    metadata:
      labels:
        k8s-app: wiki
    spec:
      containers:
        - image: registry.tech.dreamhack.se/tech/wiki:latest
          imagePullPolicy: IfNotPresent
          name: wiki
        - image: quay.io/dhtech/dhauth
          imagePullPolicy: IfNotPresent
          name: dhauth
          env:
            - name: APACHE_PROXY_PORT
              value: "8000"
            - name: LDAP_GROUP
              value: "cn=wiki,ou=groups,dc=tech,dc=dreamhack,dc=se"
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
