apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kjell
  name: kjell
  namespace: kjell
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kjell
    spec:
      containers:
      - image: quay.io/dhtech/kjell
        imagePullPolicy: Always
        name: kjell
        volumeMounts:
          - mountPath: "/config"
            name: kjell-conf
          - mountPath: "/data"
            name: kjell-sshd-key
        env:
          - name: KJELL_SUDO_GROUP
            value: "services-colo"
          - name: KJELL_ACCESS_GROUP
            value: "skalman-tech-colo"
        readinessProbe:
          tcpSocket:
            port: 22
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 15
      restartPolicy: Always
      volumes:
        - name: kjell-conf
          configMap:
            name: kjell-conf
        - name: kjell-sshd-key
          secret:
            secretName: kjell-sshd-key
            defaultMode: 256 # 0400 in decimal
