kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kjell-ssh-data
  namespace: kjell
  labels:
    k8s-app: kjell
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
