apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kjell-master-binding
  namespace: kjell
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kjell-master-role
subjects:
- kind: ServiceAccount
  name: kjell-master
  namespace: kjell
