apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kjell-master-role
  namespace: kjell
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
