---
apiVersion: v1
kind: Service
metadata:
  name: kjell
  namespace: kjell
  labels:
    k8s-app: kjell
spec:
  externalIPs:
  - 77.80.255.102
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    k8s-app: kjell
  type: ClusterIP

