apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
spec:
  tls:
  - secretName: grafana-ingress-tls
    hosts:
    - grafana.tech.dreamhack.se
  rules:
  - host: grafana.tech.dreamhack.se
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
