apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretName: grafana-ingress-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: grafana.tech.dreamhack.se
  dnsNames:
  - grafana.tech.dreamhack.se
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - grafana.tech.dreamhack.se
