apiVersion: v1
kind: Service
metadata:
    labels:
        k8s-app: gitlab
    name: gitlab
    namespace: gitlab
spec:
    ports:
    - name: registry
      port: 8105
      targetPort: registry
    - name: workhorse
      port: 8005
      targetPort: workhorse
    selector:
        k8s-app: gitlab
    type: ClusterIP
