apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
    labels:
        k8s-app: gitlab
    name: gitlab-postgres
    namespace: gitlab
spec:
    replicas: 1
    serviceName: "gitlab-postgres"
    template:
        metadata:
            labels:
                k8s-app: gitlab
        spec:
            containers:
            - name: postgres
              image: postgres:10
              imagePullPolicy: Always
              env:
              - name: DB_USER
                value: gitlab
              - name: DB_PASS
                valueFrom:
                    secretKeyRef:
                        name: gitlab
                        key: DB_PASS
              - name: DB_NAME
                value: gitlab
              - name: DB_EXTENSION
                value: pg_trgm
              ports:
              - name: postgres
                containerPort: 5432
              volumeMounts:
              - mountPath: "/var/lib/postgresql"
                name: data
              livenessProbe:
                exec:
                    command:
                    - pg_isready
                    - -h
                    - localhost
                    - -U
                    - postgres
                initialDelaySeconds: 30
                timeoutSeconds: 5
              readinessProbe:
                exec:
                    command:
                    - pg_isready
                    - -h
                    - localhost
                    - -U
                    - postgres
                initialDelaySeconds: 30
                timeoutSeconds: 5
            volumes:
            - name: data
              persistentVolumeClaim:
                claimName: gitlab-postgres-data

