apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        k8s-app: gitlab
    name: gitlab-postgres-data
    namespace: gitlab
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
