apiVersion: v1
kind: Service
metadata:
    labels:
        k8s-app: gitlab
    name: gitlab-postgres
    namespace: gitlab
spec:
    ports:
    - name: postgres
      port: 5432
      targetPort: postgres
    selector:
        name: gitlab-postgres
