kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    k8s-app: gitlab
  name: redis-data
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
