apiVersion: v1
kind: Service
metadata:
    labels:
        k8s-app: gitlab
    name: gitlab-redis
    namespace: gitlab
spec:
    ports:
    - name: redis
      port: 6379
      targetPort: redis
    selector:
        name: gitlab-redis
