apiVersion: v1
kind: Secret
metadata:
    labels:
        k8s-app: gitlab
    name: gitlab
    namespace: gitlab
type: Opaque
data:
    gitlab-root-password: #TODO
    DB_PASS: #TODO
    health-token: #TODO 
    GITHUB_APP_ID: #TODO
    GITHUB_APP_SECRET: #TODO
