apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pyirkbot-data-writer
  namespace: pyirkbot
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - pyirkbot-data
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pyirkbot
  namespace: pyirkbot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pyirkbot-data-writer
subjects:
- kind: ServiceAccount
  name: default
  namespace: pyirkbot
