kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-data
  namespace: kjell
  labels:
    k8s-app: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Gi
