---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: kjell
  labels:
    k8s-app: storage
spec:
  externalIPs:
  - 77.80.255.103
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    k8s-app: storage
  type: ClusterIP

