apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
  namespace: rocketchat
  labels:
    k8s-app: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rocketchat
  template:
    metadata:
      labels:
        k8s-app: rocketchat
    spec:
      containers:
      - name: rocketchat
        image: rocketchat/rocket.chat:0.70.3
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: rocketchat
              key: mongodb-url
        - name: MONGO_OPLOG_URL
          valueFrom:
            secretKeyRef:
              name: rocketchat
              key: mongodb-oplog-url
        - name: ROOT_URL
          value: https://rocketchat.tech.dreamhack.se
