apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rocketchat-ldap-admin
  namespace: rocketchar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: cn=rocketchat-team,ou=groups,dc=colo,dc=dreamhack,dc=se
