kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-fed-data
  namespace: monitoring
  labels:
    k8s-app: prometheus-fed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
