apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    k8s-app: oops
  name: oops
  namespace: monitoring
spec:
  replicas: 1
  serviceName: "oops"
  template:
    metadata:
      labels:
        k8s-app: oops
    spec:
      containers:
      - image: quay.io/dhtech/oops
        imagePullPolicy: Always
        name: oops
        volumeMounts:
        - mountPath: "/backend/instance"
          name: oops-data
      - image: quay.io/dhtech/dhauth
        imagePullPolicy: Always
        name: dhauth
        env:
        - name: APACHE_PROXY_PORT
          value: "5002" 
        - name: LDAP_GROUP
          value: "cn=tech,ou=groups,dc=event,dc=dreamhack,dc=se"
      restartPolicy: Always
      volumes:
        - name: oops-data
          persistentVolumeClaim:
            claimName: oops-data
