kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oops-data
  namespace: monitoring
  labels:
    k8s-app: oops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
