apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: enroll-user
  namespace: enroll-user
spec:
  secretName: enroll-user-ingress-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: enroll.tech.dreamhack.se
  dnsNames:
  - enroll.tech.dreamhack.se
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - enroll.tech.dreamhack.se
