apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: ldap
  name: ldap
  namespace: ldap
spec:
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: 389
  selector:
    k8s-app: ldap
  sessionAffinity: None
  type: ClusterIP
