apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    k8s-app: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cert-manager
  template:
    metadata:
      labels:
        k8s-app: cert-manager
    spec:
      serviceAccountName: cert-manager
      containers:
        - name: cert-manager
          image: quay.io/dhtech/cert-manager-controller:grpc2
          imagePullPolicy: IfNotPresent
          args:
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=$(POD_NAMESPACE)
          # TODO(bluecmd): Only needed for the kube-lego migration
          - --default-issuer-name=letsencrypt
          - --default-issuer-kind=ClusterIssuer
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
