apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: services@tech.dreamhack.se
    privateKeySecretRef:
      name: letsencrypt-private-key
    http01: {}
