apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: services@tech.dreamhack.se
    privateKeySecretRef:
      name: letsencrypt-private-key
    dns01:
      providers:
        - name: dhdns
          grpc:
            useTLS: true
            # TODO(bluecmd): Right now cert-manager seems to not support
            # GRPCLB
            #service: dns:///dns.net.dreamhack.se
            service: dns.net.dreamhack.se:443
            serverName: dns.net.dreamhack.se
            clientCertificateSecretRef:
              name: dhdns-grpc
              key: certificate
            clientCertificateKeySecretRef:
              name: dhdns-grpc
              key: key
            timeout: 5m
            interval: 10s
