apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: node-exporter
    namespace: monitoring
spec:
    template:
        metadata:
            labels:
                k8s-app: node-exporter 
            name: node-exporter
        spec:
            containers:
            - image: prom/node-exporter
              name: node-exporter
              args:
              - --collector.diskstats.ignored-devices="^(ram|loop|fd)\\d+$"
              - --collector.ksmd
              - --collector.logind
              - --collector.systemd
              - --collector.interrupts
              - --collector.ntp
              - --collector.tcpstat
              ports:
              - containerPort: 9100
                hostPort: 9100
                name: scrape
              volumeMounts:
              - name: root-disk
                mountPath: /root-disk
                readOnly: true
            tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
              operator: Exists
            volumes:
            - name: root-disk
              hostPath:
                path: /
            hostNetwork: True
            hostPID: true


